MODEL:
    RESULTS:
        KoBERT_26_CrossEntropy : checkpoint-6500
        KoBERT_26_FocalLoss : checkpoint-6000
        KoBERT_26_WeightedCrossEntropy : checkpoint-6500
        KoBERT_32_CrossEntropy : checkpoint-6000
        KoBERT_32_FocalLoss : checkpoint-6500
        KoELECTRA_26_CrossEntropy : checkpoint-6000
        KoELECTRA_26_FocalLoss : checkpoint-6500
        KoELECTRA_26_WeightedCrossEntropy : checkpoint-6000
        KoELECTRA_32_CrossEntropy : checkpoint-6500
        KoELECTRA_32_FocalLoss : checkpoint-6000
        RoBERTa_26_CrossEntropy : checkpoint-6500
        RoBERTa_26_FocalLoss : checkpoint-6000
        RoBERTa_26_WeightedCrossEntropy : checkpoint-6500
        RoBERTa_32_CrossEntropy : checkpoint-6000
        RoBERTa_32_FocalLoss : checkpoint-6500

    pretrained_link: 
        KoBERT: kykim/bert-kor-base
        KoELECTRA: monologg/koelectra-base-v3-discriminator
        RoBERTa: klue/roberta-base
    
    num_of_classes: 19

TEST:
    DIRECTORY : 
        dataset : uncased
    CHECKPOINT_PATH : 'checkpoint-6500'

LABELING:
    0: '교육'
    1: '교통/자동차'
    2: '기타소비'
    3: '대형마트'
    4: '미용'
    5: '배달'
    6: '보험'
    7: '생필품'
    8: '생활서비스'
    9: '세금/공과금'
    10: '쇼핑몰'
    11: '여행/숙박'
    12: '외식'
    13: '의료/건강'
    14: '주류/펍'
    15: '취미/여가'
    16: '카페'
    17: '통신'
    18: '편의점'